In [1]:
from datetime import datetime
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import cufflinks as cf

In [2]:
names=['sensorType','uid','epoch','sensorReading']
df = pd.read_csv('bpm.csv',names = names)

In [3]:
df

   sensorType         uid       epoch  sensorReading
0           B         NaN  1555442715            169
1           B  15AG1A0425  1555442800            111
2           B  15AG1A0425  1555442813             74
3           B  15AG1A0425  1555443311            107
4           B  15AG1A0425  1555446194             87
5           B  15AG1A0425  1555446207            112
6           B  15AG1A0425  1555446220             93
7           B  15AG1A0425  1555446263             61
8           B  15AG1A0425  1555446275             68
9           B  15AG1A0425  1555446286             68
10          B  15AG1A0425  1555446297             95
11          B  15AG1A0425  1555446309            108
12          B  15AG1A0425  1555446319             62
13          B  15AG1A0425  1555446330             71
14          B         NaN  1555446377             81
15          B  15AG1A0425  1555446417             74
16          B  15AG1A0425  1555446428             91
17          B  15AG1A0425  1555446439             88
18          B  15AG1A0425  1555446451             78
19          B  15AG1A0425  1555446462             77
20          B  15AG1A0425  1555446498             86
21          B         NaN  1555503301            104
22          B         NaN  1555503393            132
23          B         NaN  1555503411              0
24          B         NaN  1555503423             38
25          B         NaN  1555503944            113
26          B         NaN  1555504369             66
27          B         NaN  1555505634             68
28          B         NaN  1555506259             54
29          B         NaN  1555506420              0
30          B         NaN  1555506442            174
31          B  15AG1A0425  1555506458              0
32          B  15AG1A0425  1555506479              0
33          B  15AG1A0425  1555506497             60
34          B         NaN  1555587926            121
35          B         NaN  1555588335            143
36          B  15AG1A0425  1555588514              0

In [4]:
df= df.replace(0,80)

df['epoch'] = pd.to_datetime(df.epoch,unit='s')

#df['date'] = pd.to_datetime(df['epoch']).dt.date
#df['time'] = pd.to_datetime(df['epoch']).dt.time

In [5]:
df.dtypes

sensorType               object
uid                      object
epoch            datetime64[ns]
sensorReading             int64
dtype: object

In [6]:
df = df.drop(columns=['sensorType'])
#df = df[['uid','date','time','sensorReading']]

In [7]:
df

           uid               epoch  sensorReading
0          NaN 2019-04-16 19:25:15            169
1   15AG1A0425 2019-04-16 19:26:40            111
2   15AG1A0425 2019-04-16 19:26:53             74
3   15AG1A0425 2019-04-16 19:35:11            107
4   15AG1A0425 2019-04-16 20:23:14             87
5   15AG1A0425 2019-04-16 20:23:27            112
6   15AG1A0425 2019-04-16 20:23:40             93
7   15AG1A0425 2019-04-16 20:24:23             61
8   15AG1A0425 2019-04-16 20:24:35             68
9   15AG1A0425 2019-04-16 20:24:46             68
10  15AG1A0425 2019-04-16 20:24:57             95
11  15AG1A0425 2019-04-16 20:25:09            108
12  15AG1A0425 2019-04-16 20:25:19             62
13  15AG1A0425 2019-04-16 20:25:30             71
14         NaN 2019-04-16 20:26:17             81
15  15AG1A0425 2019-04-16 20:26:57             74
16  15AG1A0425 2019-04-16 20:27:08             91
17  15AG1A0425 2019-04-16 20:27:19             88
18  15AG1A0425 2019-04-16 20:27:31             78
19  15AG1A0425 2019-04-16 20:27:42             77
20  15AG1A0425 2019-04-16 20:28:18             86
21         NaN 2019-04-17 12:15:01            104
22         NaN 2019-04-17 12:16:33            132
23         NaN 2019-04-17 12:16:51             80
24         NaN 2019-04-17 12:17:03             38
25         NaN 2019-04-17 12:25:44            113
26         NaN 2019-04-17 12:32:49             66
27         NaN 2019-04-17 12:53:54             68
28         NaN 2019-04-17 13:04:19             54
29         NaN 2019-04-17 13:07:00             80
30         NaN 2019-04-17 13:07:22            174
31  15AG1A0425 2019-04-17 13:07:38             80
32  15AG1A0425 2019-04-17 13:07:59             80
33  15AG1A0425 2019-04-17 13:08:17             60
34         NaN 2019-04-18 11:45:26            121
35         NaN 2019-04-18 11:52:15            143
36  15AG1A0425 2019-04-18 11:55:14             80

In [8]:
#df.plot(x='time',y='sensorReading',style=['o'],linestyle='-')
df.plot(x='epcoh',y='sensorReading',style=['o'])

KeyError: 'epcoh'